const sampleData = [
  // Approved Movies
  {
    title: 'The Dark Knight',
    type: 'Movie',
    director: 'Christopher Nolan',
    budget: 185000000,
    location: 'Hollywood',
    duration: '152 min',
    releaseYear: 2008,
    status: 'approved',
  },
  {
    title: 'Pulp Fiction',
    type: 'Movie',
    director: 'Quentin Tarantino',
    budget: 8000000,
    location: 'Hollywood',
    duration: '154 min',
    releaseYear: 1994,
    status: 'approved',
  },
  {
    title: 'Forrest Gump',
    type: 'Movie',
    director: 'Robert Zemeckis',
    budget: 55000000,
    location: 'Hollywood',
    duration: '142 min',
    releaseYear: 1994,
    status: 'approved',
  },
  {
    title: 'The Matrix',
    type: 'Movie',
    director: 'The Wachowskis',
    budget: 63000000,
    location: 'Hollywood',
    duration: '136 min',
    releaseYear: 1999,
    status: 'approved',
  },
  {
    title: 'Parasite',
    type: 'Movie',
    director: 'Bong Joon Ho',
    budget: 11000000,
    location: 'Korean Cinema',
    duration: '132 min',
    releaseYear: 2019,
    status: 'approved',
  },
  {
    title: 'Gladiator',
    type: 'Movie',
    director: 'Ridley Scott',
    budget: 103000000,
    location: 'Hollywood',
    duration: '155 min',
    releaseYear: 2000,
    status: 'approved',
  },
  {
    title: '3 Idiots',
    type: 'Movie',
    director: 'Rajkumar Hirani',
    budget: 12000000,
    location: 'Bollywood',
    duration: '170 min',
    releaseYear: 2009,
    status: 'approved',
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    type: 'Movie',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    budget: 90000000,
    location: 'Hollywood',
    duration: '117 min',
    releaseYear: 2018,
    status: 'approved',
  },
  // Approved TV Shows
  {
    title: 'Game of Thrones',
    type: 'TV Show',
    director: 'David Benioff, D. B. Weiss',
    budget: 15000000,
    location: 'Hollywood',
    duration: '8 Seasons',
    releaseYear: 2011,
    status: 'approved',
  },
  {
    title: 'Stranger Things',
    type: 'TV Show',
    director: 'The Duffer Brothers',
    budget: 8000000,
    location: 'Hollywood',
    duration: '4 Seasons',
    releaseYear: 2016,
    status: 'approved',
  },
  {
    title: 'The Office (US)',
    type: 'TV Show',
    director: 'Greg Daniels',
    budget: 2000000,
    location: 'Hollywood',
    duration: '9 Seasons',
    releaseYear: 2005,
    status: 'approved',
  },
  {
    title: 'Chernobyl',
    type: 'TV Show',
    director: 'Johan Renck',
    budget: 50000000,
    location: 'Hollywood',
    duration: '1 Miniseries',
    releaseYear: 2019,
    status: 'approved',
  },
  {
    title: 'Fleabag',
    type: 'TV Show',
    director: 'Phoebe Waller-Bridge',
    budget: 1000000,
    location: 'British Cinema',
    duration: '2 Seasons',
    releaseYear: 2016,
    status: 'approved',
  },
  {
    title: 'Money Heist',
    type: 'TV Show',
    director: 'Álex Pina',
    budget: 2000000,
    location: 'Spanish Cinema',
    duration: '5 Parts',
    releaseYear: 2017,
    status: 'approved',
  },
  // Pending Movies
  {
    title: 'Dune: Part Two',
    type: 'Movie',
    director: 'Denis Villeneuve',
    budget: 190000000,
    location: 'Hollywood',
    duration: '166 min',
    releaseYear: 2024,
    status: 'pending',
  },
  {
    title: 'Joker',
    type: 'Movie',
    director: 'Todd Phillips',
    budget: 55000000,
    location: 'Hollywood',
    duration: '122 min',
    releaseYear: 2019,
    status: 'pending',
  },
  {
    title: 'RRR',
    type: 'Movie',
    director: 'S. S. Rajamouli',
    budget: 72000000,
    location: 'Tollywood',
    duration: '182 min',
    releaseYear: 2022,
    status: 'pending',
  },
  // Pending TV Shows
  {
    title: 'The Mandalorian',
    type: 'TV Show',
    director: 'Jon Favreau',
    budget: 15000000,
    location: 'Hollywood',
    duration: '3 Seasons',
    releaseYear: 2019,
    status: 'pending',
  },
  {
    title: 'Squid Game',
    type: 'TV Show',
    director: 'Hwang Dong-hyuk',
    budget: 21400000,
    location: 'Korean Cinema',
    duration: '1 Season',
    releaseYear: 2021,
    status: 'pending',
  },
  // Rejected Entry for testing
  {
    title: 'The Last Airbender',
    type: 'Movie',
    director: 'M. Night Shyamalan',
    budget: 150000000,
    location: 'Hollywood',
    duration: '103 min',
    releaseYear: 2010,
    status: 'rejected',
  },
];

export default sampleData;

